<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="yaroshenko" name="ua.st.selenium.LoginTest" tests="5" failures="0" timestamp="03 апр 2018 14:21:16 GMT" time="0.010" errors="1">
  <testcase name="mayBeLogout" time="0.010" classname="ua.st.selenium.LoginTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerExceptionat ua.st.selenium.LoginTest.mayBeLogout(LoginTest.java:18)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeMethod(Invoker.java:516)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)]]>
    </error>
  </testcase> <!-- mayBeLogout -->
  <testcase name="testLoginUserNotOkInvalidEmail" time="0.000" classname="ua.st.selenium.LoginTest">
    <skipped/>
  </testcase> <!-- testLoginUserNotOkInvalidEmail -->
  <testcase name="testLoginUserNotOkEmptyEmailAndPassword" time="0.000" classname="ua.st.selenium.LoginTest">
    <skipped/>
  </testcase> <!-- testLoginUserNotOkEmptyEmailAndPassword -->
  <testcase name="testLoginUserOk" time="0.000" classname="ua.st.selenium.LoginTest">
    <skipped/>
  </testcase> <!-- testLoginUserOk -->
  <testcase name="testLoginFirmOk" time="0.000" classname="ua.st.selenium.LoginTest">
    <skipped/>
  </testcase> <!-- testLoginFirmOk -->
</testsuite> <!-- ua.st.selenium.LoginTest -->
